## 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

## 2. Print the NUMPY version and the configuration.

In [2]:
print('Numpy version', np.__version__)

Numpy version 1.24.3


# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
a = np.random.random((2, 3, 5))  # Primera manera

a = np.empty((2, 3 ,5))    # Segunda manera
for i in range(2):
    for x in range(3):
        for y in range(5):
            a[i, x, y] = np.random.rand()

            
a = np.random.random(2 * 3 * 5).reshape(2, 3, 5)   # Tercera manera


# 4. Print a.

In [4]:
print(a)


[[[0.78754251 0.73500811 0.49297638 0.59210843 0.48785049]
  [0.45336241 0.19366173 0.99133695 0.479313   0.35565686]
  [0.65034137 0.16156531 0.02987792 0.06489909 0.8948922 ]]

 [[0.81447173 0.07809962 0.47053149 0.73259234 0.90151888]
  [0.21957248 0.13851765 0.71197649 0.87938879 0.03038052]
  [0.07135804 0.96312277 0.39457378 0.01484534 0.08212302]]]



# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
# Assign the array to variable "b"

In [5]:
b = np.empty((5, 2 ,3))    
for i in range(5):
    for x in range(2):
        for y in range(3):
            b [i, x, y] = 1

# 6. Print b.

In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



# 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
b.size == a.size

True


# 8. Are you able to add a and b? Why or why not?

In [8]:
# No se pueden sumar porque su shape no es la misma.

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [9]:
c = b.transpose ((1, 2, 0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [10]:
d = a + c
d

array([[[1.78754251, 1.73500811, 1.49297638, 1.59210843, 1.48785049],
        [1.45336241, 1.19366173, 1.99133695, 1.479313  , 1.35565686],
        [1.65034137, 1.16156531, 1.02987792, 1.06489909, 1.8948922 ]],

       [[1.81447173, 1.07809962, 1.47053149, 1.73259234, 1.90151888],
        [1.21957248, 1.13851765, 1.71197649, 1.87938879, 1.03038052],
        [1.07135804, 1.96312277, 1.39457378, 1.01484534, 1.08212302]]])

# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [11]:
print(a)
print(d)

# A la segunda matriz se le incrementa cada elemento en 1

[[[0.78754251 0.73500811 0.49297638 0.59210843 0.48785049]
  [0.45336241 0.19366173 0.99133695 0.479313   0.35565686]
  [0.65034137 0.16156531 0.02987792 0.06489909 0.8948922 ]]

 [[0.81447173 0.07809962 0.47053149 0.73259234 0.90151888]
  [0.21957248 0.13851765 0.71197649 0.87938879 0.03038052]
  [0.07135804 0.96312277 0.39457378 0.01484534 0.08212302]]]
[[[1.78754251 1.73500811 1.49297638 1.59210843 1.48785049]
  [1.45336241 1.19366173 1.99133695 1.479313   1.35565686]
  [1.65034137 1.16156531 1.02987792 1.06489909 1.8948922 ]]

 [[1.81447173 1.07809962 1.47053149 1.73259234 1.90151888]
  [1.21957248 1.13851765 1.71197649 1.87938879 1.03038052]
  [1.07135804 1.96312277 1.39457378 1.01484534 1.08212302]]]


# 12. Multiply a and c. Assign the result to e.

In [12]:
e = a * c
e

array([[[0.78754251, 0.73500811, 0.49297638, 0.59210843, 0.48785049],
        [0.45336241, 0.19366173, 0.99133695, 0.479313  , 0.35565686],
        [0.65034137, 0.16156531, 0.02987792, 0.06489909, 0.8948922 ]],

       [[0.81447173, 0.07809962, 0.47053149, 0.73259234, 0.90151888],
        [0.21957248, 0.13851765, 0.71197649, 0.87938879, 0.03038052],
        [0.07135804, 0.96312277, 0.39457378, 0.01484534, 0.08212302]]])

# 13. Does e equal to a? Why or why not?

In [13]:
e == a # Porque se ha multiplicado por 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [14]:
d_max = d.max()
d_max

1.9913369480648409

In [15]:
d_min = d.min()
d_min

1.014845342910288

In [16]:
d_mean = d.mean()
d_mean

1.4624488573617211

# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [17]:
f = np.empty(d.shape)
f

array([[[0.78754251, 0.73500811, 0.49297638, 0.59210843, 0.48785049],
        [0.45336241, 0.19366173, 0.99133695, 0.479313  , 0.35565686],
        [0.65034137, 0.16156531, 0.02987792, 0.06489909, 0.8948922 ]],

       [[0.81447173, 0.07809962, 0.47053149, 0.73259234, 0.90151888],
        [0.21957248, 0.13851765, 0.71197649, 0.87938879, 0.03038052],
        [0.07135804, 0.96312277, 0.39457378, 0.01484534, 0.08212302]]])


# 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.




In [18]:
for i in range(2):
    for x in range(3):
        for y in range(5):
            if d[i][x][y] > d_min and d[i][x][y] < d_mean:
                f[i][x][y] = 25
            elif d[i][x][y] > d_mean and d[i][x][y] < d_max:
                f[i][x][y] = 75
            elif d[i][x][y] == d_mean:
                f[i][x][y] = 50
            elif d[i][x][y] == d_min:
                f[i][x][y] = 0
            elif d[i][x][y] == d_max:
                f[i][x][y] = 100






# 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [19]:
print(d)
print(f)

[[[1.78754251 1.73500811 1.49297638 1.59210843 1.48785049]
  [1.45336241 1.19366173 1.99133695 1.479313   1.35565686]
  [1.65034137 1.16156531 1.02987792 1.06489909 1.8948922 ]]

 [[1.81447173 1.07809962 1.47053149 1.73259234 1.90151888]
  [1.21957248 1.13851765 1.71197649 1.87938879 1.03038052]
  [1.07135804 1.96312277 1.39457378 1.01484534 1.08212302]]]
[[[ 75.  75.  75.  75.  75.]
  [ 25.  25. 100.  75.  25.]
  [ 75.  25.  25.  25.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  75.  75.  25.]
  [ 25.  75.  25.   0.  25.]]]



## 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 

("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.


In [22]:
new_values = {
    0: "A",
    25: "B",
    50: "C",
    75: "D",
    100: "E"
}

nueva_matriz = []

for row in f:
    new_row = [new_values[value] for value in row]
    nueva_matriz.append(new_row)

for row in nueva_matriz:
    print(row)

TypeError: unhashable type: 'numpy.ndarray'